-- Orbit SQLite Schema
-- Single source of truth for all operational tracking data.
-- Applied via db/migrations/0001_initial.sql on first run.
-- Do NOT edit this file directly; add a new migration instead.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- ─── Migration tracking ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS schema_migrations (
    version     INTEGER PRIMARY KEY,
    applied_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ─── Application pipeline ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pipeline_entries (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    seq_no       INTEGER NOT NULL UNIQUE,
    applied_date TEXT    NOT NULL,                          -- ISO date YYYY-MM-DD
    company      TEXT    NOT NULL,
    role         TEXT    NOT NULL,
    source       TEXT    NOT NULL,
    status       TEXT    NOT NULL CHECK (status IN (
                     'Evaluated', 'Applied', 'Responded',
                     'Interview', 'Offer', 'Rejected', 'Discarded', 'SKIP'
                 )),
    rate         TEXT,                                      -- nullable; hourly or annual
    pdf_path     TEXT,                                      -- relative path to submitted PDF
    eval_id      INTEGER REFERENCES offer_evaluations (id), -- FK to most recent evaluation
    notes        TEXT,
    created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_pipeline_status  ON pipeline_entries (status);
CREATE INDEX IF NOT EXISTS idx_pipeline_company ON pipeline_entries (company, role);

-- ─── Offer evaluations ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS offer_evaluations (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    company               TEXT    NOT NULL,
    role                  TEXT    NOT NULL,
    eval_date             TEXT    NOT NULL,                 -- ISO date
    -- Five weighted scoring dimensions (A / B / C / Skip)
    technical_match       TEXT    NOT NULL CHECK (technical_match       IN ('A','B','C','Skip')),
    seniority_alignment   TEXT    NOT NULL CHECK (seniority_alignment   IN ('A','B','C','Skip')),
    archetype_fit         TEXT    NOT NULL CHECK (archetype_fit         IN ('A','B','C','Skip')),
    compensation_fairness TEXT    NOT NULL CHECK (compensation_fairness IN ('A','B','C','Skip')),
    market_demand         TEXT    NOT NULL CHECK (market_demand         IN ('A','B','C','Skip')),
    -- Legacy numeric dimension columns (added by migration 0002; kept here for schema completeness)
    dim_technical         REAL    NOT NULL DEFAULT 0.0,
    dim_seniority         REAL    NOT NULL DEFAULT 0.0,
    dim_archetype_fit     REAL    NOT NULL DEFAULT 0.0,
    dim_compensation      REAL    NOT NULL DEFAULT 0.0,
    dim_market_demand     REAL    NOT NULL DEFAULT 0.0,
    -- Computed score and outcome
    score                 REAL    NOT NULL CHECK (score >= 0.0 AND score <= 5.0),
    label                 TEXT    NOT NULL CHECK (label IN ('Priority', 'Viable', 'Low Fit')),
    recommended_action    TEXT    NOT NULL CHECK (recommended_action IN ('Tailor', 'Watch', 'Skip')),
    -- Qualitative notes (one text block; sections delimited by headings inside the value)
    notes                 TEXT,
    -- Versioning: new re-evaluations increment version; old row points forward via superseded_by
    version               INTEGER NOT NULL DEFAULT 1,
    superseded_by         INTEGER REFERENCES offer_evaluations (id),
    evaluated_at          TEXT    NOT NULL DEFAULT (datetime('now')),
    created_at            TEXT    NOT NULL DEFAULT (datetime('now')),
    -- L2-009 AC3: scores below 3.0 must result in Skip at the database layer
    CHECK (score >= 3.0 OR recommended_action = 'Skip')
);

CREATE INDEX IF NOT EXISTS idx_eval_company_role ON offer_evaluations (company, role);

-- ─── Job search runs ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS scan_runs (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    run_date         TEXT    NOT NULL,                      -- ISO date
    total_results    INTEGER NOT NULL DEFAULT 0,
    new_listings     INTEGER NOT NULL DEFAULT 0,
    seen_listings    INTEGER NOT NULL DEFAULT 0,
    boards_searched  TEXT,                                  -- JSON array of board names
    keywords         TEXT,                                  -- search keywords used
    notes            TEXT,
    created_at       TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ─── Job listings ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS job_listings (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    scan_run_id           INTEGER REFERENCES scan_runs (id),
    title                 TEXT    NOT NULL,
    company               TEXT    NOT NULL,
    source                TEXT    NOT NULL,                 -- board / portal / recruiter name
    posted_date           TEXT,                             -- ISO date; nullable if not published
    rate                  TEXT,                             -- explicit rate string or NULL
    url                   TEXT,
    ats_type              TEXT,                             -- ATS platform name
    archetype             TEXT    NOT NULL DEFAULT 'Enterprise Contract' CHECK (archetype IN (
                              'Enterprise Contract', 'Product Company',
                              'Consulting Firm', 'AI / Innovation',
                              'Government / Public Sector'
                          )),
    archetype_inferred    INTEGER NOT NULL DEFAULT 1 CHECK (archetype_inferred IN (0,1)),
    auto_score            REAL,                             -- pre-evaluation fit estimate
    is_stale              INTEGER NOT NULL DEFAULT 0 CHECK (is_stale IN (0,1)),
    is_priority_recruiter INTEGER NOT NULL DEFAULT 0 CHECK (is_priority_recruiter IN (0,1)),
    status                TEXT    NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Seen', 'Applied', 'Archived')),
    first_seen_date       TEXT    NOT NULL,
    last_seen_date        TEXT    NOT NULL,
    UNIQUE (company, title)                                 -- deduplication key
);

CREATE INDEX IF NOT EXISTS idx_listings_scan_run ON job_listings (scan_run_id);
CREATE INDEX IF NOT EXISTS idx_listings_status   ON job_listings (status);

-- ─── Compensation estimates ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS compensation_estimates (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id      INTEGER NOT NULL UNIQUE REFERENCES job_listings (id),
    range_low       REAL,                                   -- NULL means no data found
    range_high      REAL,
    currency        TEXT    NOT NULL DEFAULT 'CAD',
    unit            TEXT    NOT NULL DEFAULT 'hr' CHECK (unit IN ('hr', 'yr')),
    confidence      TEXT    CHECK (confidence IN ('High', 'Medium', 'Low')),
    source          TEXT    NOT NULL,                       -- "No data found" when unavailable
    researched_date TEXT    NOT NULL,                       -- ISO date; re-research if > 30 days
    estimated_at    TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ─── Recruiter contacts ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS recruiter_contacts (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    firm_name            TEXT    NOT NULL UNIQUE,
    contact_name         TEXT,
    contact_linkedin     TEXT,
    priority_tier        TEXT    NOT NULL DEFAULT 'Medium' CHECK (priority_tier IN ('High', 'Medium', 'Low')),
    opportunity_page_url TEXT,
    last_contacted_date  TEXT,                              -- ISO date
    engagement_status    TEXT    NOT NULL DEFAULT 'Active' CHECK (engagement_status IN ('Active', 'Passive', 'Dormant', 'Closed')),
    notes                TEXT,
    created_at           TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at           TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ─── Target accounts ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS target_accounts (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    name                 TEXT    NOT NULL UNIQUE,
    company              TEXT,                              -- alias for 'name'; set by migration 0002
    career_page_url      TEXT,
    ats_type             TEXT    CHECK (ats_type IN (
                             'Greenhouse', 'Ashby', 'Lever', 'Wellfound', 'Workable', NULL
                         )),
    priority             TEXT    NOT NULL DEFAULT 'Medium' CHECK (priority IN ('High', 'Medium', 'Low')),
    recruiter_contact_id INTEGER REFERENCES recruiter_contacts (id),
    notes                TEXT,
    created_at           TEXT    NOT NULL DEFAULT (datetime('now'))
);

-- ─── Interview story bank ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS interview_stories (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT    NOT NULL,
    context     TEXT    NOT NULL,                           -- company / role / time period
    situation   TEXT    NOT NULL,
    task        TEXT    NOT NULL,
    action      TEXT    NOT NULL,
    result      TEXT    NOT NULL,
    reflection  TEXT    NOT NULL,
    skills      TEXT    NOT NULL DEFAULT '[]',              -- JSON array
    keywords    TEXT    NOT NULL DEFAULT '[]',              -- JSON array; used for overlap matching
    created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
    -- No UPDATE or DELETE: append-only by convention
);

-- ─── Outreach records ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS outreach_records (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id  INTEGER REFERENCES job_listings (id),
    company     TEXT    NOT NULL,
    role        TEXT    NOT NULL,
    file_path   TEXT    NOT NULL,                           -- relative path to .txt file
    type        TEXT    NOT NULL DEFAULT 'linkedin-message'
                    CHECK (type IN ('linkedin-message', 'email', 'follow-up')),
    version     INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_outreach_listing ON outreach_records (listing_id);
